<?php
declare(strict_types=1);

// OnePiece SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OnePieceUtility::setRegistrar(function (OnePieceUtility $u): void {
    $u->clean = [OnePieceClean::class, 'call'];
    $u->done = [OnePieceDone::class, 'call'];
    $u->make_error = [OnePieceMakeError::class, 'call'];
    $u->feature_add = [OnePieceFeatureAdd::class, 'call'];
    $u->feature_hook = [OnePieceFeatureHook::class, 'call'];
    $u->feature_init = [OnePieceFeatureInit::class, 'call'];
    $u->fetcher = [OnePieceFetcher::class, 'call'];
    $u->make_fetch_def = [OnePieceMakeFetchDef::class, 'call'];
    $u->make_context = [OnePieceMakeContext::class, 'call'];
    $u->make_options = [OnePieceMakeOptions::class, 'call'];
    $u->make_request = [OnePieceMakeRequest::class, 'call'];
    $u->make_response = [OnePieceMakeResponse::class, 'call'];
    $u->make_result = [OnePieceMakeResult::class, 'call'];
    $u->make_point = [OnePieceMakePoint::class, 'call'];
    $u->make_spec = [OnePieceMakeSpec::class, 'call'];
    $u->make_url = [OnePieceMakeUrl::class, 'call'];
    $u->param = [OnePieceParam::class, 'call'];
    $u->prepare_auth = [OnePiecePrepareAuth::class, 'call'];
    $u->prepare_body = [OnePiecePrepareBody::class, 'call'];
    $u->prepare_headers = [OnePiecePrepareHeaders::class, 'call'];
    $u->prepare_method = [OnePiecePrepareMethod::class, 'call'];
    $u->prepare_params = [OnePiecePrepareParams::class, 'call'];
    $u->prepare_path = [OnePiecePreparePath::class, 'call'];
    $u->prepare_query = [OnePiecePrepareQuery::class, 'call'];
    $u->graphql_body = [OnePieceGraphql::class, 'body'];
    $u->graphql_errors = [OnePieceGraphql::class, 'errors'];
    $u->result_basic = [OnePieceResultBasic::class, 'call'];
    $u->result_body = [OnePieceResultBody::class, 'call'];
    $u->result_headers = [OnePieceResultHeaders::class, 'call'];
    $u->transform_request = [OnePieceTransformRequest::class, 'call'];
    $u->transform_response = [OnePieceTransformResponse::class, 'call'];
});
